#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${NAVIGATOR_PROJECT_ROOT:-$(cd -- "$SCRIPT_DIR/.." && pwd)}"
MANIFEST_DIR="${NAVIGATOR_MANIFEST_DIR:-experiments/navigator-nnunet-v2}"
TRAIN_MANIFEST="${NAVIGATOR_TRAIN_MANIFEST:-$MANIFEST_DIR/train.txt}"
VALIDATION_MANIFEST="${NAVIGATOR_VALIDATION_MANIFEST:-$MANIFEST_DIR/validation.txt}"
UNIT="${NAVIGATOR_DIAGNOSTIC_UNIT:-navigator-g1-diagnostic-250k-v3}"
CHECKPOINT_DIR="${NAVIGATOR_CHECKPOINT_DIR:-checkpoints/navigator-g1-diagnostic-250k-v3}"
VALIDATION_OUTPUT_DIR="${NAVIGATOR_VALIDATION_OUTPUT_DIR:-results/navigator_nnunet/g1-diagnostic-250k-v3-validation}"

cd "$PROJECT_ROOT"
if [[ ! -s "$TRAIN_MANIFEST" ]]; then
  echo "Missing immutable train manifest: $PROJECT_ROOT/$TRAIN_MANIFEST" >&2
  exit 1
fi
if [[ ! -s "$VALIDATION_MANIFEST" ]]; then
  echo "Missing immutable validation manifest: $PROJECT_ROOT/$VALIDATION_MANIFEST" >&2
  exit 1
fi
for output in "$CHECKPOINT_DIR" "$VALIDATION_OUTPUT_DIR"; do
  if [[ -e "$output" ]]; then
    echo "Refusing to mix a new diagnostic with existing output: $PROJECT_ROOT/$output" >&2
    exit 1
  fi
done

export NAVIGATOR_TRAIN_SCRIPT=scripts/train_navigator_nnunet.sh
export NAVIGATOR_NNUNET_RAW="${NAVIGATOR_NNUNET_RAW:-data/nnunet/nnUNet_raw}"
export NAVIGATOR_NNUNET_CACHE_DIR="${NAVIGATOR_NNUNET_CACHE_DIR:-results/navigator_nnunet/cache}"
export NAVIGATOR_NNUNET_TRAIN_CASE_IDS_FILE="$TRAIN_MANIFEST"
export NAVIGATOR_NNUNET_VAL_CASE_IDS_FILE="$VALIDATION_MANIFEST"
export NAVIGATOR_CHECKPOINT_DIR="$CHECKPOINT_DIR"
export NAVIGATOR_VALIDATION_OUTPUT_DIR="$VALIDATION_OUTPUT_DIR"
export NAVIGATOR_TOTAL_TIMESTEPS="${NAVIGATOR_TOTAL_TIMESTEPS:-250000}"
export NAVIGATOR_GENERATE_EXPERT_PATH=1
export NAVIGATOR_BEHAVIOR_CLONING_EPOCHS="${NAVIGATOR_BEHAVIOR_CLONING_EPOCHS:-1}"
export NAVIGATOR_BC_MAX_POLICY_PROBABILITY="${NAVIGATOR_BC_MAX_POLICY_PROBABILITY:-0}"
export NAVIGATOR_PATH_RADIUS_MM=9
export NAVIGATOR_ENDPOINT_TOLERANCE_MM=3
export NAVIGATOR_MAX_EPISODE_STEPS="${NAVIGATOR_MAX_EPISODE_STEPS:-2048}"
export NAVIGATOR_FRAMES_PER_BATCH="${NAVIGATOR_FRAMES_PER_BATCH:-1024}"
export NAVIGATOR_BATCH_SIZE="${NAVIGATOR_BATCH_SIZE:-128}"
export NAVIGATOR_UPDATE_EPOCHS="${NAVIGATOR_UPDATE_EPOCHS:-1}"
export NAVIGATOR_LEARNING_RATE="${NAVIGATOR_LEARNING_RATE:-0.00005}"
export NAVIGATOR_GDT_REWARD_SCALE="${NAVIGATOR_GDT_REWARD_SCALE:-1}"
export NAVIGATOR_EVAL_INTERVAL="${NAVIGATOR_EVAL_INTERVAL:-25}"
export NAVIGATOR_SAVE_FREQ="${NAVIGATOR_SAVE_FREQ:-25}"

exec scripts/navigator_systemd.sh start "$UNIT"
